apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-ruler-config
  namespace: monitoring
data:
  loki.yaml: |
    ruler:
      alertmanager_url: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
      enable_api: true
      enable_alertmanager_v2: true
      evaluation_interval: 1m
      poll_interval: 1m
      ring:
        kvstore:
          store: inmemory
      rule_path: /tmp/loki/rules-temp
      storage:
        type: local
        local:
          directory: /etc/loki/rules 