tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  retention: 24h
  reportingEnabled: false

multitenancy:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1
    memory: 1Gi 