apiVersion: batch/v1
kind: CronJob
metadata:
  name: wordpress-backup
  namespace: wordpress
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: wordpress-backup-pvc
            - name: wp-content
              persistentVolumeClaim:
                claimName: wordpress-data
          containers:
            - name: backup
              image: bitnami/mariadb:latest
              command:
                - "/bin/bash"
                - "-c"
                - |
                  # Create backup directory with timestamp
                  TIMESTAMP=$(date +%Y%m%d%H%M%S)
                  BACKUP_DIR="/backups/$TIMESTAMP"
                  mkdir -p $BACKUP_DIR

                  # Set MySQL password as environment variable
                  export MYSQL_PWD=${MYSQL_PASSWORD}
                  
                  # Backup database
                  mysqldump -h wordpress-mysql -u wordpress --skip-ssl --no-tablespaces --skip-triggers --databases wordpress > $BACKUP_DIR/wordpress-db.sql
                  
                  # Backup WordPress files
                  cp -r /wp-content/* $BACKUP_DIR/
                  
                  # Compress backup
                  cd /backups
                  tar -zcf wordpress-backup-$TIMESTAMP.tar.gz $TIMESTAMP
                  rm -rf $TIMESTAMP
                  
                  # Clean up old backups (keep last 7)
                  cd /backups
                  ls -t | grep wordpress-backup | tail -n +8 | xargs rm -f

                  echo "Backup completed successfully: wordpress-backup-$TIMESTAMP.tar.gz"
              env:
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: wordpress-db-credentials
                      key: db_password
              volumeMounts:
                - name: backup-volume
                  mountPath: /backups
                - name: wp-content
                  mountPath: /wp-content
                  readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-backup-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 