apiVersion: batch/v1
kind: Job
metadata:
  name: wordpress-upload-divi-configmap
  namespace: wordpress
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: upload-divi
        image: debian:bullseye-slim
        command:
        - /bin/bash
        - -c
        - "chmod +x /scripts/upload-script.sh && /scripts/upload-script.sh"
        env:
        - name: DIVI_URL
          value: "" # Optional: URL to download Divi theme
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
        - mountPath: /divi
          name: divi-theme-volume
        - mountPath: /scripts
          name: script-volume
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-data
      - name: divi-theme-volume
        emptyDir: {}
      - name: script-volume
        configMap:
          name: divi-theme-uploader
          defaultMode: 0755
---
# To use this job, you need to copy the Divi.zip file to the pod first using kubectl cp:
# kubectl cp /path/to/Divi.zip UPLOAD_POD_NAME:/divi/Divi.zip -n wordpress
#
# Get the upload pod name with:
# kubectl get pods -n wordpress -l job-name=wordpress-upload-divi-configmap 