apiVersion: batch/v1
kind: Job
metadata:
  name: wordpress-upload-divi-lowmem
  namespace: wordpress
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: upload-divi
        image: debian:bullseye-slim
        command:
        - /bin/bash
        - -c
        - |
          # Install necessary tools
          apt-get update && apt-get install -y wget unzip curl pv
          
          # Prepare the themes directory
          echo "Creating directories..."
          mkdir -p /var/www/html/wp-content/themes/Divi

          # Navigate to temporary directory to save space
          cd /tmp
          
          # If a URL is provided, download the Divi theme in chunks
          if [ -n "$DIVI_URL" ]; then
            echo "Downloading Divi theme from URL..."
            # Using wget with the --continue flag to support resuming downloads
            wget --continue -O Divi.zip "$DIVI_URL"
          else
            echo "No DIVI_URL provided. Please mount Divi.zip or provide a download URL."
            if [ -f /divi/Divi.zip ]; then
              echo "Found mounted Divi.zip, using it..."
              
              # Instead of copying the whole file, create a symlink to save memory
              ln -sf /divi/Divi.zip Divi.zip
            fi
          fi
          
          # Check if file exists
          if [ ! -f Divi.zip ] && [ ! -L Divi.zip ]; then
            echo "Failed to get Divi.zip file. Exiting."
            exit 1
          fi
          
          # Get file size for monitoring
          FILE_SIZE=$(stat -c%s "Divi.zip" 2>/dev/null || stat -f%z "Divi.zip")
          echo "Divi.zip file size: $(( FILE_SIZE / 1024 / 1024 )) MB"
          
          # Extract the theme directly to target using streaming to minimize memory usage
          echo "Extracting Divi theme (streaming mode)..."
          mkdir -p /var/www/html/wp-content/themes/Divi.tmp
          
          # Use a streaming approach to unzip without loading the entire file into memory
          unzip -q -d /var/www/html/wp-content/themes/Divi.tmp Divi.zip
          
          # Move extracted files to final location
          echo "Moving files to final location..."
          if [ -d "/var/www/html/wp-content/themes/Divi.tmp/Divi" ]; then
            # If Divi is inside another directory, move it up
            rm -rf /var/www/html/wp-content/themes/Divi
            mv /var/www/html/wp-content/themes/Divi.tmp/Divi /var/www/html/wp-content/themes/
          else
            # If files are directly in the temp dir, rename it
            rm -rf /var/www/html/wp-content/themes/Divi
            mv /var/www/html/wp-content/themes/Divi.tmp /var/www/html/wp-content/themes/Divi
          fi
          
          # Check if extraction was successful
          if [ ! -d "/var/www/html/wp-content/themes/Divi" ]; then
            echo "Failed to extract Divi theme. Exiting."
            exit 1
          fi
          
          # Fix permissions
          echo "Setting proper permissions..."
          chown -R www-data:www-data /var/www/html/wp-content/themes/Divi
          chmod -R 755 /var/www/html/wp-content/themes/Divi
          
          # Clean up
          echo "Cleaning up..."
          if [ -L Divi.zip ]; then
            # If it's a symlink, just remove the link
            rm Divi.zip
          else
            # Remove the actual file
            rm -f Divi.zip
          fi
          rmdir /var/www/html/wp-content/themes/Divi.tmp 2>/dev/null || true
          
          echo "Divi theme installed successfully!"
        env:
        - name: DIVI_URL
          value: "" # Optional: URL to download Divi theme
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
        - mountPath: /divi
          name: divi-theme-volume
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-data
      - name: divi-theme-volume
        emptyDir: {}
---
# This low-memory variant is designed for large themes that might cause OOM issues.
# To use this job, you need to copy the Divi.zip file to the pod:
# kubectl cp /path/to/Divi.zip UPLOAD_POD_NAME:/divi/Divi.zip -n wordpress
#
# Get the upload pod name with:
# kubectl get pods -n wordpress -l job-name=wordpress-upload-divi-lowmem 