apiVersion: batch/v1
kind: Job
metadata:
  name: wordpress-upload-divi
  namespace: wordpress
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: upload-divi
        image: debian:bullseye-slim
        command:
        - /bin/bash
        - -c
        - |
          # Install necessary tools
          apt-get update && apt-get install -y wget unzip curl
          
          # Prepare the themes directory
          mkdir -p /var/www/html/wp-content/themes/Divi

          # Navigate to temporary directory to save space
          cd /tmp
          
          # Download Divi theme (replace with actual URL if needed)
          echo "Downloading Divi theme..."
          # Using wget with the -O flag to name the output file
          if [ -n "$DIVI_URL" ]; then
            wget -O Divi.zip "$DIVI_URL"
          else
            echo "No DIVI_URL provided. Please mount Divi.zip or provide a download URL."
            [ -f /divi/Divi.zip ] && cp /divi/Divi.zip .
          fi
          
          # Check if file exists
          if [ ! -f Divi.zip ]; then
            echo "Failed to get Divi.zip file. Exiting."
            exit 1
          fi
          
          # Extract the theme directly to the target directory to avoid using extra memory
          echo "Extracting Divi theme..."
          unzip -o Divi.zip -d /var/www/html/wp-content/themes/
          
          # Check if extraction was successful
          if [ ! -d "/var/www/html/wp-content/themes/Divi" ]; then
            echo "Failed to extract Divi theme. Exiting."
            exit 1
          fi
          
          # Fix permissions
          echo "Setting proper permissions..."
          chown -R www-data:www-data /var/www/html/wp-content/themes/Divi
          chmod -R 755 /var/www/html/wp-content/themes/Divi
          
          # Clean up
          echo "Cleaning up..."
          rm Divi.zip
          
          echo "Divi theme installed successfully!"
        env:
        - name: DIVI_URL
          value: "" # Optional: URL to download Divi theme
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
        - mountPath: /divi
          name: divi-theme-volume
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-data
      - name: divi-theme-volume
        emptyDir: {}
---
# To use this job, you need to copy the Divi.zip file to the pod first using kubectl cp:
# kubectl cp /path/to/Divi.zip UPLOAD_POD_NAME:/divi/Divi.zip -n wordpress
#
# Get the upload pod name with:
# kubectl get pods -n wordpress -l job-name=wordpress-upload-divi 