apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-memcached-config
  namespace: wordpress
data:
  wp-config-memcached.php: |
    <?php
    /**
     * WordPress Memcached Configuration
     */
    
    // Memcached settings
    define('WP_CACHE', true);
    
    // Add memcached support
    define('MEMCACHED_SERVERS', 'memcached.wordpress.svc.cluster.local:11211');
    
    // Enable object caching - This will be loaded by the Memcached Object Cache plugin
    $memcached_servers = array(
        'default' => array(
            'memcached.wordpress.svc.cluster.local:11211'
        )
    );
    
    // Enable memcached for database cache
    define('DB_CACHE', true);
    
    // Memcached plugin configuration
    define('WP_CACHE_KEY_SALT', 'wp_');
    
    // Only allow server-side connections - no external connections
    define('MEMCACHED_ONLY_INTERNAL', true); 