{
 "title": "MySQL Dashboard",
 "tags": [ "mysql" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mysql_up{namespace=\"wordpress\"}",
     "legendFormat": "MySQL Status"
    }
   ]
  },
  {
   "title": "MySQL Queries/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions{namespace=\"wordpress\"}[5m])",
     "legendFormat": "Queries/sec"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysql_global_status_bytes_sent{namespace=\"wordpress\"}",
     "legendFormat": "Bytes Sent"
    },
    {
     "expr": "mysql_global_status_bytes_received{namespace=\"wordpress\"}",
     "legendFormat": "Bytes Received"
    }
   ]
  },
  {
   "title": "MySQL Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{namespace=\"wordpress\"}",
     "legendFormat": "Connected Threads"
    },
    {
     "expr": "mysql_global_status_threads_running{namespace=\"wordpress\"}",
     "legendFormat": "Running Threads"
    }
   ]
  }
 ]
}