apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ntfy-templates
  namespace: monitoring
data:
  ntfy-message-template.tmpl: |
    {{ define "ntfy.default.message" }}
    {{ if gt (len .Alerts.Firing) 0 }}🔥 {{ .Alerts.Firing | len }} alert{{ if gt (len .Alerts.Firing) 1 }}s{{ end }} firing {{ end }}
    {{ if gt (len .Alerts.Resolved) 0 }}✅ {{ .Alerts.Resolved | len }} alert{{ if gt (len .Alerts.Resolved) 1 }}s{{ end }} resolved {{ end }}
    {{ range .Alerts.Firing }}
    {{ .Labels.alertname }}: {{ .Annotations.summary }}
    {{ end }}
    {{ range .Alerts.Resolved }}
    RESOLVED: {{ .Labels.alertname }}
    {{ end }}
    {{ end }}

  ntfy-title-template.tmpl: |
    {{ define "ntfy.default.title" }}
    {{ if gt (len .Alerts.Firing) 0 }}
    {{ if eq (len .Alerts.Firing) 1 }}{{ (index .Alerts.Firing 0).Labels.alertname }}{{ else }}Multiple Alerts Firing{{ end }}
    {{ else }}
    {{ if eq (len .Alerts.Resolved) 1 }}{{ (index .Alerts.Resolved 0).Labels.alertname }} Resolved{{ else }}Multiple Alerts Resolved{{ end }}
    {{ end }}
    {{ end }}

  ntfy-tags-template.tmpl: |
    {{ define "ntfy.default.tags" }}
    {{ if gt (len .Alerts.Firing) 0 }}warning,alert{{ else }}success,resolved{{ end }}
    {{ end }}

  ntfy-priority-template.tmpl: |
    {{ define "ntfy.default.priority" }}
    {{ if gt (len .Alerts.Firing) 0 }}
    {{ $severity := "" }}
    {{ range .Alerts.Firing }}{{ if eq .Labels.severity "critical" }}{{ $severity = "urgent" }}{{ end }}{{ end }}
    {{ if eq $severity "urgent" }}urgent{{ else }}high{{ end }}
    {{ else }}
    default
    {{ end }}
    {{ end }}

  webhook-config.json: |
    {
      "template_files": {
        "ntfy.default.message": "{{ define \"ntfy.default.message\" }}\n{{ if gt (len .Alerts.Firing) 0 }}🔥 {{ .Alerts.Firing | len }} alert{{ if gt (len .Alerts.Firing) 1 }}s{{ end }} firing {{ end }}\n{{ if gt (len .Alerts.Resolved) 0 }}✅ {{ .Alerts.Resolved | len }} alert{{ if gt (len .Alerts.Resolved) 1 }}s{{ end }} resolved {{ end }}\n{{ range .Alerts.Firing }}\n{{ .Labels.alertname }}: {{ .Annotations.summary }}\n{{ end }}\n{{ range .Alerts.Resolved }}\nRESOLVED: {{ .Labels.alertname }}\n{{ end }}\n{{ end }}",
        "ntfy.default.title": "{{ define \"ntfy.default.title\" }}\n{{ if gt (len .Alerts.Firing) 0 }}\n{{ if eq (len .Alerts.Firing) 1 }}{{ (index .Alerts.Firing 0).Labels.alertname }}{{ else }}Multiple Alerts Firing{{ end }}\n{{ else }}\n{{ if eq (len .Alerts.Resolved) 1 }}{{ (index .Alerts.Resolved 0).Labels.alertname }} Resolved{{ else }}Multiple Alerts Resolved{{ end }}\n{{ end }}\n{{ end }}",
        "ntfy.default.tags": "{{ define \"ntfy.default.tags\" }}\n{{ if gt (len .Alerts.Firing) 0 }}warning,alert{{ else }}success,resolved{{ end }}\n{{ end }}",
        "ntfy.default.priority": "{{ define \"ntfy.default.priority\" }}\n{{ if gt (len .Alerts.Firing) 0 }}\n{{ $severity := \"\" }}\n{{ range .Alerts.Firing }}{{ if eq .Labels.severity \"critical\" }}{{ $severity = \"urgent\" }}{{ end }}{{ end }}\n{{ if eq $severity \"urgent\" }}urgent{{ else }}high{{ end }}\n{{ else }}\ndefault\n{{ end }}\n{{ end }}"
      },
      "headers": {
        "Title": "{{ template \"ntfy.default.title\" . }}",
        "Tags": "{{ template \"ntfy.default.tags\" . }}",
        "Priority": "{{ template \"ntfy.default.priority\" . }}"
      },
      "body": "{{ template \"ntfy.default.message\" . }}"
    } 