apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  valuesContent: |-
    grafana:
      grafana.ini:
        server:
          root_url: "%(protocol)s://%(domain)s/grafana"
          serve_from_sub_path: true 