apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  admin-user: eGFsZw==  # Base64 encoded 'xalg'
  admin-password: UHIxYW1zZjBsbHkh  # Base64 encoded password 