apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-basic-auth-config
  namespace: monitoring
data:
  grafana.ini: |
    [security]
    disable_initial_admin_creation = false
    
    [auth]
    disable_login_form = false
    disable_signout_menu = false
    oauth_auto_login = false
    oauth_allow_insecure_email_lookup = false
    login_maximum_inactive_lifetime_duration = 30d
    login_maximum_lifetime_duration = 30d
    
    [auth.basic]
    enabled = true
    
    [auth.proxy]
    enabled = false
    
    [auth.oauth]
    enabled = false
    
    [auth.ldap]
    enabled = false
    
    [auth.jwt]
    enabled = false
    
    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Admin 