apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-secret
  namespace: n8n
type: Opaque
data:
  DB_TYPE: c3FsaXRl  # sqlite
  DB_SQLITE_PATH: L2hvbWUvbm9kZS8ubjhuL2RhdGFiYXNlLnNxbGl0ZQ==  # /home/node/.n8n/database.sqlite
  N8N_BASIC_AUTH_ACTIVE: dHJ1ZQ==  # true
  N8N_BASIC_AUTH_USER: YWRtaW5AZXhhbXBsZS5jb20=  # admin@example.com
  N8N_BASIC_AUTH_PASSWORD: QWRtaW4xMjM0NTYh  # Admin123456!
  N8N_RUNNERS_ENABLED: dHJ1ZQ==  # true
  N8N_METRICS_ENABLED: dHJ1ZQ==  # true 