apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: n8n
  namespaceSelector:
    matchNames:
      - n8n
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http 